name: Terraform Infrastructure Deploy

on:
  push:
    paths:
    - 'terraform/**'
    - '.github/workflows/infra-deploy.yml'
  workflow_dispatch:


jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Terraform Init
      run: terraform init

    - name: Terraform Format
      run: terraform fmt -check

    - name: Terraform Validate
      run: terraform validate

    - name: Terraform Plan
      run: terraform plan -input=false
    # To enable apply, uncomment below:
    # - name: Terraform Apply
    #   run: terraform apply -auto-approve
